services:
  # Головна база даних PostgreSQL(Master)
  db:
    image: postgres:16-alpine
    container_name: traveler_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-1234}
      POSTGRES_DB: TravelerDB
    ports:
      - "5433:5432"
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_replication_slots=10"
      - "-c"
      - "max_wal_senders=10"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-migrations:ro
      - ./db/replications/publisher:/docker-entrypoint-replications:ro
      - ./db/replications/common:/docker-entrypoint-initdb.d:ro
    networks: [traveler_net]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

    # Репліка (Slave)
  db_replica:
    image: postgres:16-alpine
    container_name: traveler_replica
    user: postgres
    environment:
      PGPASSWORD: rep_pass
    volumes:
      - postgres_replica_data:/var/lib/postgresql/data
    ports:
      - "55433:5432"
    entrypoint: [ "bash", "-c", "
          if [ ! -s /var/lib/postgresql/data/PG_VERSION ]; then
            echo 'Cloning Master...';
            export PGAPPNAME=traveler_replica;
            until pg_basebackup -h db -U repuser -D /var/lib/postgresql/data -Fp -Xs -R; do
              echo 'Master not ready for backup, waiting...';
              rm -rf /var/lib/postgresql/data/*;
              sleep 2;
            done;
            echo 'Clone successful!';
            chmod 0700 /var/lib/postgresql/data;
          fi;
          exec postgres -c wal_level=logical -c application_name=traveler_replica -c hot_standby=on" ]
    networks: [traveler_net]
    depends_on:
      db:
        condition: service_healthy

  # Репліка 2 (Slave2)
  db_replica_2:
    image: postgres:16-alpine
    container_name: traveler_replica_2
    user: postgres
    environment:
      PGPASSWORD: rep_pass
    volumes:
      - postgres_replica_2_data:/var/lib/postgresql/data
    ports:
      - "55434:5432"
    entrypoint: [ "bash", "-c", "
          set -e;
          if [ ! -s /var/lib/postgresql/data/PG_VERSION ]; then
            export PGAPPNAME=traveler_replica_2;
            until pg_basebackup -h db -U repuser -D /var/lib/postgresql/data -Fp -Xs -R; do
              rm -rf /var/lib/postgresql/data/*;
              sleep 2;
            done;
            chmod 0700 /var/lib/postgresql/data;
          fi;
          exec postgres -c wal_level=logical -c application_name=traveler_replica_2 -c hot_standby=on" ]
    networks: [traveler_net]
    depends_on:
      db:
        condition: service_healthy

  # Ваш Spring Boot додаток
  app:
    build: .
    container_name: traveler_api
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/TravelerDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-1234}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks: [traveler_net]
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  postgres_replica_data:
  postgres_replica_2_data:

networks:
  traveler_net:
    driver: bridge