services:
  # Головна база даних PostgreSQL(Master)
  db:
    image: postgres:16-alpine
    container_name: traveler_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-1234}
      POSTGRES_DB: TravelerDB
    ports:
      - "5433:5432"
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_replication_slots=10"
      - "-c"
      - "max_wal_senders=10"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-migrations:ro
      - ./db/replications/publisher:/docker-entrypoint-replications:ro
      - ./db/replications/common:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # Репліка (Slave)
  db_replica:
    image: postgres:16-alpine
    container_name: traveler_replica
    user: postgres
    environment:
      PGPASSWORD: rep_pass
    volumes:
      - postgres_replica_data:/var/lib/postgresql/data
    ports:
      - "55433:5432"
    entrypoint: [ "bash", "-c", "
          if [ ! -s /var/lib/postgresql/data/PG_VERSION ]; then
            echo 'Cloning master for physical replication...';
            until pg_basebackup -h db -U repuser -D /var/lib/postgresql/data -Fp -Xs -R; do
              echo 'Master not ready, retrying...';
              sleep 2;
            done;
            chmod 0700 /var/lib/postgresql/data;
          fi;
          exec postgres -c wal_level=logical" ]
    depends_on:
      db:
        condition: service_healthy


  # Ваш Spring Boot додаток
  app:
    build: .
    container_name: traveler_api
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/TravelerDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-1234}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  postgres_replica_data: